### ISSUE TITLE
Random C2-12828-1 error

### ISSUE THREAD

**Issue by littlebalup** [usineur/ZeldaROTH#2] opened 2017-10-03 17:31 UTC
Hi,
I got this error many times, mainly when re-loading game or during screen/map loading. Reproduced on both PSVITA / PSTV and both henkaku / enso, without any extra plugin.

Thx ;)

**Comment by usineur** [comment] 2017-10-03 23:57
Hi,

I wasn't able to reproduce this. Just try on a fresh build for nearly 45 mins, no problem during map loading... No crash at all in fact.

What do you mean exactly by "reloading" ? Pressing "Vita home" button, performing some actions then resuming the game ?

Let me know your env too:
 - Are you using some "exotic" plugins ?
 - Enso ?

Random errors are the worst, if you find a more precise scenario, I would help with pleasure.

**Comment by littlebalup** [comment] 2017-10-04 04:58
By reloading I mean by exiting current game with the start button menu, then reload the save or strart a new game. So, without closing the application. You can try this to reproduce, generally the error occurs after 5 or 6 loops:
- load a save or start a new game
- press start then exit (with or without  saving)
- reload a save or start a new game
- press start then exit
Etc...

P.S.: I don't use any extra plugins.

**Comment by usineur** [comment] 2017-10-04 23:21
> By reloading I mean by exiting current game with the start button menu, then reload the save or strart a new game. So, without closing the application. You can try this to reproduce, generally the error occurs after 5 or 6 loops:
>
> - load a save or start a new game
> - press start then exit (with or without saving)
> - reload a save or start a new game
> - press start then exit
> -Etc...

Ok, that's what I call a pretty good reproductible scenario case. :)

I think I have identified the problem, which comes from the original engine.
Could you try this [eboot.bin](https://www.ferb.fr/vita/eboot.bin) (overwrite the one in `ux0:app/ZERO00001/`) and give me some feedbacks ?

> Another video showing a random crash in game (this time, after more than five minutes game) :
> https://youtu.be/-_K7SGUxAlA
> Associated core dump:
> psp2core-1507125954-0x0008cf3c1b-eboot.bin.psp2dmp.zip

May be fixed in the above mentionned eboot.bin, but not really sure, so I'm waiting for your feedbacks here too. Thx.

**Comment by littlebalup** [comment] 2017-10-05 15:02
yes, you got it !  :)
Two hours that I'm stressing the game as much as I can. No more crash at all.

What was the issue? A kind of overflow memory buffer?
Anyway, please, commit the fix as soon as you can. So, I'll add it to my french forked version.

P.S.: about my fork, if you didn't figured out yet, I moddified a little bit the "keyboard" code to use analog stick instead of D-pad for link movements (using SDL_JoystickGetAxis() ). So liberate some buttons for missing stuffs like monsters encyclopedia access, look arround, etc. : https://github.com/littlebalup/ZeldaROTH/commit/ee8fc993ac387907dc73bbd60b035213e8550e94
And it works great.

Encore merci ;)

**Comment by usineur** [comment] 2017-10-05 16:13
> yes, you got it ! :)
> Two hours that I'm stressing the game as much as I can. No more crash at all.
> 
> What was the issue? A kind of overflow memory buffer?

Some objects are re-instanced without freeing the old ones. This caused some memory leaks gathering that is pretty invisible on a PC due to the larger amount of RAM than a Vita.

> Anyway, please, commit the fix as soon as you can. So, I'll add it to my french forked version.

Revisions: de3211f9d1d3fbf8e1aa8bcaccb176ea71937d3d and dd2c7aaa16926b81cff414170d2dc02954f43064

> P.S.: about my fork, if you didn't figured out yet, I moddified a little bit the "keyboard" code to use analog stick instead of D-pad for link movements (using SDL_JoystickGetAxis() ). So liberate some buttons for missing stuffs like monsters encyclopedia access, look arround, etc. : littlebalup/ZeldaROTH@ee8fc99
And it works great.

Nice.

>Encore merci ;)

De rien.

**Closed** 2017-10-05 16:43 UTC
